###/login
POST http://localhost:3000/api/login
Content-Type: application/json

{ 
"username":"tester01",
"password":"GteteqbQQgSr88SwNExUQv2ydb7xuf8c"
}
###Clients-GET,POST, PUT and DELETE
GET http://localhost:3000/api/clients
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"48b551a376e9a54fcedaa07f5de8e949"}
### 
POST http://localhost:3000/api/client/new
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"6e24e0fa90239f501086063997a35d08"}

{
    "name": "Armalinda",
    "email": "testemail@hotmail.com",
    "telephone": "0998877665"
}

###
PUT http://localhost:3000/api/client/1
Content-Type: application/json
X-user-auth: {"username": "tester01", "token":"e7be661d66890cc2d91cc3f44fd93d41"}

{
    "name": "Jonas TEST1 ",
    "email": "TEST46@hotmail.com",
    "telephone": "(883) 400-5800 x08714"
}

###
DELETE http://localhost:3000/api/client/2
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"8ec337707db84553b897cbd2b776ccf4"}

###Rooms-GET,POST, PUT and DELETE
GET http://localhost:3000/api/rooms
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"8d619b69de30a579e73390c30925476c"}

### 
POST http://localhost:3000/api/room/1
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"f8eb38ab313110b51e0ac75dcc22d395"}

{
    "features": [
        "balcony"
    ],
    "category": "double",
    "number": "1",
    "floor": "1",
    "available": true,
    "price": "1"
}
###
PUT http://localhost:3000/api/room/1
Content-Type: application/json
X-user-auth: {"username":"tester01","token":"576b6f536c40eeb0a57dab881282cd83"}

{
    "features": [
        "balcony"
    ],
    "category": "test",
    "number": "5",
    "floor": "1",
    "available": true,
    "price": "1"
}